// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMCgHvGZ1eT1ofnutpJV_b4zvsk8V9X5k',
    appId: '1:579957371784:web:16c9e6f37419c6d743803d',
    messagingSenderId: '579957371784',
    projectId: 'health-chats-bfb93',
    authDomain: 'health-chats-bfb93.firebaseapp.com',
    databaseURL: 'https://health-chats-bfb93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-chats-bfb93.appspot.com',
    measurementId: 'G-JWFV6SF5QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrdXre3UI3UEJQpso5cziuHdkXHyPWe2E',
    appId: '1:579957371784:android:bd07f0fcb4e83c1f43803d',
    messagingSenderId: '579957371784',
    projectId: 'health-chats-bfb93',
    databaseURL: 'https://health-chats-bfb93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-chats-bfb93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr41flGxewy15-8Iu8csSaam1SgsqaLBQ',
    appId: '1:579957371784:ios:fec3c58e74949d8243803d',
    messagingSenderId: '579957371784',
    projectId: 'health-chats-bfb93',
    databaseURL: 'https://health-chats-bfb93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-chats-bfb93.appspot.com',
    iosClientId: '579957371784-l2ffs0jaa2f3cdfkli6umdhktu4mecra.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthchats',
  );
}
